### ISSUE TITLE
GS.Общие.Хранилище не должен находиться (дублироваться) в папке gedemin-prolog

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin-prolog#2]
Не хорошо, что ПИ крестики-нолики завивист от GS.Общие.Хранилище и копия последнего находится в отдельном каталоге. Так нельзя. Или зависит от GS.Общие.Хранилище и это должен быть единый файл в эталонном каталоге. Или вводите свое ПИ, со своими, специфическими данными, который будет зависеть от GS.Общие.Хранилище.

**Comment by arthur-latunov** [comment]
"и копия последнего находится в отдельном каталоге" - это давняя история,
использовал gedemin-prolog фактически для дополнительной резервной копии.
Там и vbs многие и прочее. Почищу.
В ПИ крестики-нолики установлена зависимость от  GS.Общие.Хранилище обычным
образоми.

8 мая 2015 г., 14:32 пользователь Andrej Kirejeŭ notifications@github.com
написал:
